### ISSUE TITLE
Delphi XE5 Build Error

### ISSUE THREAD

**Issue by dangas56** [TurboPack/Orpheus#1]
XE5 didnt build due to an error with LifeCycles

DataSource.DataSet.Fields.LifeCycles
I'm Guessing that LifeCycles was introduced in XE6

only seems to be an issue for these Pas Files
OvcDbIdx
Ovcdbcl
OvcDbTbl

i got it building by adding the following around the LifeCycles
{$if CompilerVersion > 26}
{$Endif}

**Comment by romankassebaum** [comment]
The idea behind moving to GitHub was to work without directives. For older Delphi versions I planned to add forks. The main fork should support the current Delphi (C++Builder) version, whereas older versions should get their own fork.

A huge advantage would be that people like you can help me since I for example do not have XE5.

That's why it would be terrific if you could modify everything (including the project files) so that it works with XE5. Don't use directives, simply modify the code.

Then you can create a pull request and I will put the code into an own fork.

-- 
Many thanks,

Roman

**Comment by dangas56** [comment]
i created a fork and made the changes so i could build Delphi XE5

and i think i made a pull request

new to Git hub
