### ISSUE TITLE
Orpheus failed to install in Delhi 10.3 Community Edition

### ISSUE THREAD

**Issue by SantiPR** [TurboPack/Orpheus#16]
Hello,

I'm trying to install Orpheus in a Delphi 10.3 Community edition but package OrpheusDR260 have internal error:

**[dcc32 Fatal Error] OvcRvExpDef.pas(2185): F2084 Internal Error: C15211**

The error line points to  _function TOvcRvExpIsTest.AsBoolean(const TestValue: Variant): Boolean;_

Any ideas?

Regards,
Santi

**Comment by rpottsoh** [comment]
I ran into this when I updated Orpheus to Delphi 10.3.  For details on all he changes I made see the PR I submitted lynxnake/TurboPower-Orpheus#2.  I didn't fork Orpheus from here.... 

Anyway, I ran into the issue you are reporting.  What I determined is that `VarIsNull` is triggering the compiler message.  The offending code appears twice in function TOvcRvExpIsTest.AsBoolean:
```pascal
Result := VarIsNull(TestValue) xor UnaryNot;
```
I determined that if I substituted that line for:
```pascal
Result := (TestValue = null) xor UnaryNot;
```
that the compiler is happy.

Again the offending logic appears twice in that function; near the top and again near the bottom.  If you refer to my PR you will see I encapsulated my change with a compiler directive so that my change is not incorporated into versions less than Delphi 10.3.  I also don't make any claims that my change to the code will work the same way as written before.  I just know that it clears the issue for the compiler.

The problem you are facing was the only real issue I faced when I was working to get Orpheus to build with Delphi 10.3.

**Comment by SantiPR** [comment]
Thank you very mach for the tip.

I was trying to install10.3Rio branch. 
I've  download master and everything run well.

Regards.

**Comment by oschubert** [comment]
I was able to compile the Orpheus package by just changing the last line in that function as described above:
Result := VarIsNull(TestValue) xor UnaryNot;
I didn't even have to change the first occurrence of it.

However, when I try to install the package I get a "Entry point not found" error message.

**Comment by andrekarnyoto** [comment]
this is also my question, thanks for your information.
[https://www.logminor.com/id/](url)
